[profile.default]
src = "src"
out = "out"
libs = [
    "node_modules/@layerzerolabs/toolbox-foundry/lib",
    "node_modules",
]
remappings = [
    "ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test",
    "forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std",
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]

[fmt]
sort_imports = true
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
quote_style = "double"
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
